- hosts: "docker"
  become: yes
  remote_user: tfuser
  become_method: sudo
  become_user: root
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:

    - name: Comment out repos 1
      lineinfile:
        dest: /etc/apt/sources.list
        state: present
        regexp: 'lunar main'
        line: '#deb http://archive.ubuntu.com/ubuntu lunar main restricted universe multiverse'  

    - name: Comment out repos 2
      lineinfile:
        dest: /etc/apt/sources.list
        state: present
        regexp: 'lunar-updates'
        line: '#deb http://archive.ubuntu.com/ubuntu lunar-updates main restricted universe multiverse'  

    - name: Comment out repos 3
      lineinfile:
        dest: /etc/apt/sources.list
        state: present
        regexp: 'lunar-security'
        line: '#deb http://archive.ubuntu.com/ubuntu lunar-security main restricted universe multiverse'                 

    - name: Create the /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG Key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker Repo to apt sources & trust
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: 'deb [trusted=yes arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu lunar stable'
        create: true


#    - name: Add Docker repo to apt sources
#      copy:
#        content: |
#          deb [arch={{ arch_mapping[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc]
#            https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
##           https://download.docker.com/linux/ubuntu         
#        dest: /etc/apt/sources.list.d/docker.list

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install Docker Packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin


        state: latest 

    - name: Install Other Packages
      apt:
        name:
          - python3-pip


        state: latest         