

---
- hosts: all"docker"
  gather_facts: no
  become: yes
  vars:
  ansible_python_interpreter: /usr/bin/python3
  

  tasks:
    - name: Build the Docker image
      community.docker.docker_image:
        name: "my-app:latest"
        build:
          path: ./my_app_directory
        source: "build"
        state: present

    - name: Run the Docker container
      community.docker.docker_container:
        name: "my-app-container"
        image: "my-app:latest"
        state: started
        restart_policy: "always" # Optional: Restart if container exits
        ports:
          - "8080:8080" # Example: Map host port 8080 to container port 8080