---

- name: Install Standard Software on Server at bootstrap
  hosts: docker
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install dnsutils
      apt:
        name: dnsutils
        state: present

